name: .NET Core Desktop

on: [push]

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 6

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: Create the app package
      run: msbuild /p:Configuration=Release /p:Version=1.2.3.4 /p:Platform=x64
      env:
        PROJECT_VERSION: ${{ steps.short-sha.outputs.sha }}

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSIX Package
        path: BypassReplacer\bin\x64\Release\
